In [26]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


In [27]:
Gender = ["male", "male", "male", "male", "female", "female", "female", "female"]
Height = [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75]
Weight = [180, 190, 170, 165, 100, 150, 130, 150]
Foot_Size = [12, 11, 12, 10, 6, 8, 7, 9]


In [28]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string into numbers.
Gender_encoded=le.fit_transform(Gender)
Height_encoded=le.fit_transform(Height)
Weight_encoded=le.fit_transform(Weight)
Foot_Size_encoded=le.fit_transform(Foot_Size)


In [29]:
features=list(zip(Gender_encoded,Height_encoded,Weight_encoded))

In [50]:

from sklearn.model_selection import train_test_split
features_train, features_test,label_train,label_test=train_test_split(features, Foot_Size_encoded, test_size=0.8, random_state=42)


In [51]:
Classifier =  DecisionTreeClassifier()

In [52]:
Classifier = Classifier.fit(features_train,label_train)

In [53]:
predicted = Classifier.predict(features_test)

In [54]:
print("Prediction:", predicted)

Prediction: [1 1 1 1 1 1 1]


In [55]:
new_entry=[[8.00 ,380,12]]

In [56]:
prediction = Classifier.predict(new_entry)

In [57]:
print("Prediction:", predicted)

Prediction: [1 1 1 1 1 1 1]


In [58]:
conf_mat = confusion_matrix(label_test, predicted)
print("Confusion Matrix:")
print(conf_mat)


Confusion Matrix:
[[0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0]]


In [60]:
accuracy = accuracy_score(label_test, predicted)
print("Accuracy:", accuracy)


Accuracy: 0.0
